import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { describe, it } from 'node:test'
import { buildStatus, callers, verifyRef } from '../docs/improvements/_build-status.mjs'

/**
 * The status file drifted once, and the drift was invisible.
 *
 * `status.md` was generated by a script that computed the tables from
 * `_status-*.json` and then appended a paragraph typed by hand: "the other four
 * are still exported, tested and called by nothing." By the time anyone read it
 * again, three of those four had production callers, one item's guard test had
 * been renamed, and the paragraph said otherwise — because a string literal does
 * not know what the tree contains. The file read as verified and was not.
 *
 * So the generator now derives the narrative and resolves every reference against
 * the tree, and this file is what keeps the committed status.md from going stale
 * the same way:
 *
 *   - the committed status.md equals what the generator produces now;
 *   - no ledger reference names a file that does not exist;
 *   - the scanner that decides "called by nothing" actually finds callers — the
 *     canary below is the point. A probe that returns [] for both "no callers"
 *     and "I never ran" would report every module as uncalled, or none.
 */

const ROOT = path.resolve(new URL('..', import.meta.url).pathname)

describe('enhancement status', () => {
  it('the committed status.md is what the generator produces now', () => {
    const { markdown } = buildStatus({ root: ROOT, write: false })
    const committed = readFileSync(path.join(ROOT, 'docs/improvements/status.md'), 'utf8')
    assert.equal(committed, markdown,
      'docs/improvements/status.md is stale — regenerate with node docs/improvements/_build-status.mjs')
  })

  it('every evidence path and guard name resolves', () => {
    const { brokenRefs } = buildStatus({ root: ROOT, write: false })
    assert.deepEqual(brokenRefs, [],
      `the ledger names files that do not exist:\n  ${brokenRefs.join('\n  ')}`)
  })

  it('the call-site scanner finds a caller that exists, and none where none does', () => {
    // Canary: escalation.js is reached *only* through app.js's `lazy()` helper —
    // no `from`/`import()` names it. A scanner that knows only `from '…'` reports
    // it uncalled, and this test is the only thing that would notice.
    assert.ok(callers('public/workflow/escalation.js', ROOT).length > 0,
      'scanner found no caller for escalation.js — it is loaded via lazy(), and a scanner that misses that is broken')
    // And the converse, so the assertion above is not passed by a scanner that
    // returns a non-empty list for everything.
    assert.equal(callers('src/agreement.js', ROOT).length, 0,
      'scanner claims agreement.js has a production caller; it is imported only by tests')
  })

  it('a reference past the end of its file is rejected', () => {
    assert.equal(verifyRef('src/server.js:999999', ROOT).ok, false)
    assert.equal(verifyRef('src/server.js:1', ROOT).ok, true)
    assert.equal(verifyRef('src/does-not-exist.js', ROOT).ok, false)
  })
})
